name: eux-avslutt-rinasaker-arkiver-naisjob
schedule: "0 5 * * *"

prosess: arkiver

application:
  eux-avslutt-rinasaker:
    name: eux-avslutt-rinasaker
    namespace: eessibasis
    endpoint: http://eux-avslutt-rinasaker
    scope: api://prod-gcp.eessibasis.eux-avslutt-rinasaker/.default
