name: eux-avslutt-rinasaker-slett-dok-utkast-naisjob
schedule: "42 14 * * *"

prosess: slett-dokumentutkast

application:
  eux-avslutt-rinasaker:
    name: eux-avslutt-rinasaker
    namespace: eessibasis
    endpoint: http://eux-avslutt-rinasaker
    scope: api://prod-gcp.eessibasis.eux-avslutt-rinasaker/.default
